### ISSUE TITLE
can't find result .

### ISSUE THREAD

**Issue by CodeMadUser** [jiahong-fu/KXNet#4]
hello,it's amazing work . But  when the running is over, I can't find the picture after processing,what should I do to look them?

**Comment by jiahong-fu** [comment]
Thanks for your attention, you need to uncomment the corresponding save code. Such as [here](https://github.com/jiahong-fu/KXNet/blob/f13c3958324a17dddefcb1a6d4b4870e358b0e0a/codes/config/KXNet/test.py#L103).

**Comment by CodeMadUser** [comment]
> Thanks for your attention, you need to uncomment the corresponding save code. Such as [here](https://github.com/jiahong-fu/KXNet/blob/f13c3958324a17dddefcb1a6d4b4870e358b0e0a/codes/config/KXNet/test.py#L103).

thank you your replying.I'll try it on.
