### ISSUE TITLE
the Supplementary Material cannot be accessed

### ISSUE THREAD

**Issue by RebornForPower** [jiahong-fu/KXNet#6]
[[Supplementary Material]](https://github.com/jiahong-fu/KXNet/blob/main)

the `[Supplementary Material]`  in your readme cannot be accessed, it shows the 404 Error!

**Comment by jiahong-fu** [comment]
Thank you for your interest in our work. I'm sorry to inform you that due to personal reasons, the additional materials were not viewable. I have now re-uploaded the supplementary materials.
