### ISSUE TITLE
setting1和setting2对于训练过程有什么区别？

### ISSUE THREAD

**Issue by YoungP2001** [jiahong-fu/KXNet#7]
您好，在Readme里面看到对于测试集setting1和2不一样，那训练过程有什么不同？为什么要设置setting1和2？

**Comment by jiahong-fu** [comment]
您好，感谢您关注我们工作！
A1: 训练代码相同，只是一些参数设置有区别；
A2: 为了验证模型有效性，我们考虑不同退化难度，setting1是针对各项同性高斯模糊核，setting2针对各项异性高斯模糊核+高斯噪声。

**Comment by YoungP2001** [comment]
> 您好，感谢您关注我们工作！ A1: 训练代码相同，只是一些参数设置有区别； A2: 为了验证模型有效性，我们考虑不同退化难度，setting1是针对各项同性高斯模糊核，setting2针对各项异性高斯模糊核+高斯噪声。

明白了，感谢！
