### ISSUE TITLE
关于测试集生成

### ISSUE THREAD

**Issue by Ada22222** [jiahong-fu/KXNet#8]
您好，请问您setting1生成的测试集是和DAN这篇工作不一样的吗？我用的在DAN上测试集测试您的KXNet，指标结果和您论文里的table1的结果差很多。虽然我看您测试的数据集好像不是lmdb格式，但这应该不是影响测试指标的主要因素吧。
![微信图片_20230606101450](https://github.com/jiahong-fu/KXNet/assets/95062822/031eabea-9d62-49db-af95-3a1527daa7bd)

**Comment by jiahong-fu** [comment]
由于下采样算子不同，与DAN测试集是不一样的。
原因：为了严格满足退化模型$y = (x \otimes k) \downarrow_s$，其中的下采样为s-fold算子(保留s*s patch内左上角元素)。我们根据这个模型重新生成了setting1测试集，在下采样时采用标准[s-fold下采样](https://github.com/jiahong-fu/KXNet/blob/15d61a749213ba291c181141b241f4649dd7be9c/codes/utils/deg_utils.py#L308)（这里DAN使用的是[bicubic下采样](https://github.com/greatlog/DAN/blob/53f9b7010ba9ee662b2abb0b33c8df3939829a9f/codes/utils/deg_utils.py#L297)）。已附上对应代码连接，感谢您关注我们工作！

**Comment by Ada22222** [comment]
> 

非常感谢您的回复~~~因为训练的时候扔进网络的是HR图像 那么训练集是不用动的对吧。只不过其他方法想要跟您做对比实验的话是要重新训练。另外，您是在setting1和setting2中都采用了s-fold下采样 的方法是吗？还是只在setting2中用了呢。
![微信截图_20230607094607](https://github.com/jiahong-fu/KXNet/assets/95062822/ef2b4841-4199-4597-adfd-e061e3a0d2aa)

**Comment by jiahong-fu** [comment]
(1) 是的，训练集不用动；对比方法需要重新跑；
(2) setting1和2都和我们论文模型对应，采用了s-fold下采样；
